import { readable } from "svelte/store";

export const faqs = readable(
    [
        {
            "id": "1",
            "question": "Why should I use a cryptocurrency trading bot?",
            "answer": "The major advantage of using a bot is that it removes human emotion from trading. Create a bot, choose your strategy and let it trade for you even while you sleep. Bots can trade on multiple exchanges with as many coins as you setup, handling complex strategies quicker than human decision."
        },
        {
            "id": "2",
            "question": "Is a cryptocurrency trading bot profitable?",
            "answer": "This is always one of the hardest questions to answer due to the number of variables in cryptocurrency trading. Short answer yes, they can be very profitable. Long answer, it depends on the strategy used and the time you invest in tweaking your settings and understanding markets. The more you learn, the more likely you are in becoming profitable."
        },
        {
            "id": "3",
            "question": "How does Scavenger Bot trade crypto?",
            "answer": "Scavenger Bot makes trades on your behalf through predefined strategies or webhook integration and receiving alerts. You grant Scavenger Bot access to your accounts on exchanges through API key access. We have tried to keep our settings to a minimum but there is some configuration that you will need to do on our website."
        },
        {
            "id": "4",
            "question": "How are my funds protected?",
            "answer": "Scavenger Bot never has control of your assets and can't withdrawal funds from any of your exchange accounts. All of your cryptocurrency stays on the exchange where the bot is trading. You can stop the bot or revoke access at any time."
        },
        {
            "id": "5",
            "question": "What will happen after the free sign up?",
            "answer": "After signing up, you will be able to run bots until the next billing cycle (every Sunday) and then have 7 days to pay any invoice. This could result in 7+ days of trial time depending on when you sign up. "
        },
        {
            "id": "6",
            "question": "Does Scavenger Bot take any fees from trades?",
            "answer": "We do not charge a subscription fee for a basic tier of service but instead charge a 15% fee of profits invoiced weekly. We only profit when you do."
        },
        {
            "id": "7",
            "question": "How do I pay my weekly invoice?",
            "answer": "Each week an invoice is posted on your account as well as sent to the email address on record for your account. These invoices are generated by Coinbase Commerce and can be paid in BTC, ETH, USDC, LTC, DAI, and DOGE. We also offer prepay options to avoid paying weekly."
        },
        {
            "id": "8",
            "question": "How do I learn more about Scavenger Bot?",
            "answer": "You can read through our documentation, watch our videos on YouTube, or join our Discord community to chat with fellow traders. If you have additional questions, ask our support team who are willing to help."
        }
    ]
);